apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ .Values.keyvaultName }}
    cloudName: ""
    tenantId: {{ .Values.azureKeyvaultTenantID }}
    {{- if eq .Values.env "local" }}
    useVMManagedIdentity: "false"
    {{- else }}
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.azureCsiClientID }}
    {{- end }}
    objects:  |
      array:
        - |
          objectName: session-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: database-url
          objectType: secret
          objectVersion: ""
        - |
          objectName: azure-storage-account-key
          objectType: secret
          objectVersion: ""
        - |
          objectName: backend-key
          objectType: secret
          objectVersion: ""
  secretObjects:
    - secretName: {{ .Values.name }}
      type: Opaque
      data:
        - objectName: session-key
          key: SESSION_KEY
        - objectName: database-url
          key: DATABASE_URL
        - objectName: azure-storage-account-key
          key: AZURE_STORAGE_ACCOUNT_KEY
        - objectName: backend-key
          key: BACKEND_KEY
